[package]
name = "zoykad/echo"
authors = ["zoykad"]
version = "0.1.2"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
license = "MIT"
include = ["default.project.json", "src", "src/**", "LICENSE", "wally.toml", "github.url"]
exclude = ["**"]

[dependencies]
Red = "red-blox/red@2.3.2"
Guard = "red-blox/guard@1.0.1"
Signal = "sleitnick/signal@2.0.1"
Trove = "sleitnick/trove@1.1.0"